development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= "redis://:#{ ENV['REDIS_PASSWORD'] }@#{ ENV['REDIS_HOST'] }:#{ ENV['REDIS_PORT'] }" %>
  channel_prefix: cable
