# Available options:
#   http://www.rubydoc.info/github/redis/redis-rb/Redis#initialize-instance_method

default:
  host: localhost
  port: 6379


development:
  db: 0

test:
  db: 1

production:
  host: <%= ENV['REDIS_HOST'] %>
  port: <%= ENV['REDIS_PORT'] %>
  password: <%= ENV['REDIS_PASSWORD'] %>
  db: 0